import type { ShotCueId } from '@/lib/shotCues';

export interface ShotTechniqueNote {
  label: string;
  text: string;
  fullText?: string;
  halfText?: string;
}

export const SHOT_TECHNIQUE_INTRO = [
  { label: 'Ball-flight rule', text: 'The clubface controls the start line, and the swing path helps create the curve. Aim the face first, then build the stance and swing shape around that face.' },
  { label: 'Inside toes', text: 'Athletic pressure through the balls and inside edges of the feet, not tipping forward onto the toes. Feel ready to move, turn and stay balanced - like ski boots.' },
];

export const DEFAULT_SHOT_TECHNIQUE: Record<ShotCueId, ShotTechniqueNote[]> = {
  driver: [
    { label: 'Shot goal', text: 'Main swing thought: Clubface first. Right foot back. Inside-back of the ball. Lead arm long. Simple cue: Aim face, close stance, swing from inside, lead arm long. Goal is a committed full driver with slight draw feel, strong launch and balanced finish.' },
    { label: 'Pre-shot routine', text: 'Stand behind the ball. Pick the final target, then a start-line spot a few feet in front. Picture the ball starting on that line and turning gently back. Make one smooth rehearsal feeling width, inside delivery and long lead arm through the finish. Step in with the clubface first.' },
    { label: 'Clubface alignment', text: 'Aim the clubface at the start-line spot first. Build the body around the clubface.' },
    { label: 'Grip alignment', text: 'Match both hands to the clubface. Lead hand secure. Trail hand fits under and alongside the lead hand. Both V lines feel matched and point between trail ear and trail shoulder. Grip pressure secure, calm and even.' },
    { label: 'Stance and alignment', text: 'Right foot back about half a shoe to one full shoe. Stance feels slightly closed to the start line. Feet, knees, hips and shoulders are organised around the draw shape.' },
    { label: 'Ball position', text: 'Ball forward, around inside the lead heel.' },
    { label: 'Feet and pressure', text: 'Pressure through the inside toes, like being ready to move in ski boots. Feel athletic, springy and ready to turn.' },
    { label: 'Posture', text: 'Tilt from the hips. Arms hang naturally. Small trail-side spine tilt, with lead shoulder slightly higher than trail shoulder.' },
    { label: 'Eye focus', text: 'Look at the inside-back quadrant of the ball. Feel the club strike from the inside-back and travel out through the start-line spot.' },
    { label: 'Takeaway', text: 'Smooth start with width. Chest, arms and club move together.' },
    { label: 'Wrist hinge', text: 'Natural wrist hinge. Width first, then the wrists set naturally as the turn continues.' },
    { label: 'Backswing', text: 'Full, wide turn. Trail hip turns behind you. Lead arm keeps width.' },
    { label: 'Transition', text: 'Pressure moves into the lead side as the arms soften and fall into position. Feel the club drop inside before turning through.' },
    { label: 'Strike', text: 'Sweep the ball from the tee with the chest slightly behind the ball.' },
    { label: 'Follow-through', text: 'Extend both arms through the ball. Lead arm feels long after impact. Chest turns fully to target.' },
  ],
  wood_hybrid: [
    { label: 'Shot goal', text: 'Main swing thought: Face first. Right foot slightly back. Slightly outside-right / forward focus. Brush through. Lead arm long. Simple cue: Aim face, pressure toes, collect it, brush through. Goal is a strong climbing flight with clean contact and slight draw feel.' },
    { label: 'Pre-shot routine', text: 'Stand behind the ball. Pick the final target and start-line spot. Picture a strong, climbing flight. Make one rehearsal feeling a shallow brush through the strike. Step in with clubface first.' },
    { label: 'Clubface alignment', text: 'Aim the clubface at the start-line spot first. Build the stance around the face.' },
    { label: 'Grip alignment', text: 'Match both hands to the clubface. Lead hand secure, trail hand fitted naturally. V lines matched between trail ear and trail shoulder. Grip pressure calm and even.' },
    { label: 'Stance and alignment', text: 'Right foot back about a quarter shoe to half a shoe. Use a small closed-stance draw feel. Stance narrower than driver but wider than short irons.' },
    { label: 'Ball position', text: 'Slightly forward of centre. 5 wood more forward; hybrid a touch forward of middle.' },
    { label: 'Feet and pressure', text: 'Pressure through the inside toes. Pressure moves into the lead side in transition.' },
    { label: 'Posture', text: 'Athletic hip tilt, arms hanging naturally, chest relaxed. Small trail-side tilt is fine, but less than driver.' },
    { label: 'Eye focus', text: 'Look slightly outside-right / just forward of the ball, on the side that helps you brush through and send the club out to the start line. Feel the club collect the ball, then brush the turf after it.' },
    { label: 'Takeaway', text: 'Smooth and wide. Chest, arms and club move together.' },
    { label: 'Wrist hinge', text: 'Natural wrist hinge. The wrists set gradually with the turn, then stay organised as the arms fall in transition.' },
    { label: 'Backswing', text: 'Full turn with width. Trail hip turns behind you.' },
    { label: 'Transition', text: 'Pressure moves lead side as the arms fall into position. Club approaches from inside while the body turns through.' },
    { label: 'Strike', text: 'Brush through the ball and continue along the start line. Strike feels shallow, clean and sweeping.' },
    { label: 'Follow-through', text: 'Turn fully through. Lead arm feels long after impact.' },
  ],
  iron_6_7: [
    { label: 'Shot goal', text: 'Main swing thought: Face first. Right foot slightly back. Grass slightly outside-right after ball. Lead arm long. Simple cue: Aim face, pressure toes, ball then turf. Goal is a clean full iron strike with slight draw feel and controlled flight.' },
    { label: 'Pre-shot routine', text: 'Stand behind the ball. Pick final target and start-line spot. Picture the ball starting on line and flying through the window. Make one rehearsal feeling ball first, then grass after the ball. Step in with clubface first.' },
    { label: 'Clubface alignment', text: 'Aim the clubface at the start-line spot first. Build the body around the face.' },
    { label: 'Grip alignment', text: 'Match both hands to the clubface. Lead hand secure, trail hand fitted naturally. V lines matched. Grip pressure secure and calm.' },
    { label: 'Stance and alignment', text: 'Right foot back about a quarter shoe to half a shoe. Use a small closed-stance draw feel. Athletic stance, narrower than driver or wood.' },
    { label: 'Ball position', text: 'Slightly forward of centre for 6 iron. Around centre to slightly forward for 7 iron.' },
    { label: 'Feet and pressure', text: 'Pressure through the inside toes. Pressure moves into the lead side before strike.' },
    { label: 'Posture', text: 'Tilt from hips, arms hanging naturally, chest relaxed. Sternum close to over the ball.' },
    { label: 'Eye focus', text: 'Look at a small patch of grass slightly outside-right and just after the ball. This supports ball-first contact while helping the club move through the start line.' },
    { label: 'Takeaway', text: 'Smooth start. Club, arms and chest move together.' },
    { label: 'Wrist hinge', text: 'Natural wrist hinge. The wrists set gradually as the body turns. Feel controlled hinge, not a forced 90-degree set.' },
    { label: 'Backswing', text: 'Full turn with controlled width. Trail hip turns behind you.' },
    { label: 'Transition', text: 'Pressure moves into lead side as arms fall into position. Club shallows slightly before the body turns through.' },
    { label: 'Strike', text: 'Strike ball first, then brush or divot the turf after the ball.' },
    { label: 'Follow-through', text: 'Turn fully through. Lead arm feels long after impact.' },
  ],
  iron_8_9: [
    { label: 'Shot goal', text: 'Main swing thought: Face first. Right foot slightly back. Ball then turf. Lead arm long. Simple cue: Aim face, pressure toes, brush through. Goal is a full short-iron shot with centred strike and controlled launch.' },
    { label: 'Pre-shot routine', text: 'Stand behind the ball. Pick target and start-line spot. Picture the ball starting on line and flying through the window. Make one rehearsal feeling ball-first contact and a brush through the turf. Step in with clubface first.' },
    { label: 'Clubface alignment', text: 'Aim the clubface at the start-line spot first. Build the stance around the face.' },
    { label: 'Grip alignment', text: 'Match both hands to the clubface. Lead hand secure, trail hand fitted naturally. V lines matched. Grip pressure secure and calm.' },
    { label: 'Stance and alignment', text: 'Right foot back only a small amount. Stance is athletic and compact. Do not over-close it with short irons.' },
    { label: 'Ball position', text: 'Around centre, or just forward of centre if that gives the best strike.' },
    { label: 'Feet and pressure', text: 'Pressure through the inside toes. Pressure moves into lead side before impact.' },
    { label: 'Posture', text: 'Tilt from hips, arms hanging naturally, chest relaxed.' },
    { label: 'Eye focus', text: 'Look at the front-inside of the ball or the grass slightly forward/outside-right. Feel the club brush through after impact.' },
    { label: 'Takeaway', text: 'Smooth start. Club, arms and chest move together.' },
    { label: 'Wrist hinge', text: 'Natural wrist hinge. The wrists set with the turn and stay matched to the body.' },
    { label: 'Backswing', text: 'Full turn with controlled width. Trail hip turns behind you.' },
    { label: 'Transition', text: 'Pressure moves into lead side as arms fall into position. Chest turns through the strike.' },
    { label: 'Strike', text: 'Strike ball first, then brush or divot the turf after the ball.' },
    { label: 'Follow-through', text: 'Turn fully through. Lead arm feels long after impact.' },
  ],
  punch: [
    { label: 'Shot goal', text: 'Main swing thought: Face first. Lead side. Hands ahead. 9 o’clock. Turn through low. Simple cue: Aim face, 9 o’clock, turn through low. Goal is a controlled low punch with ball-first strike and reduced height.' },
    { label: 'Clock length', text: 'Use roughly a 9 o’clock backswing. Lead arm works to about parallel with the ground, then the body turns through to a controlled low finish.' },
    { label: 'Pre-shot routine', text: 'Stand behind the ball. Pick target and low start-line window. Picture the ball launching lower and running forward. Make one 9 o’clock rehearsal with hands ahead and chest turning. Step in with clubface first.' },
    { label: 'Clubface alignment', text: 'Aim clubface at the start-line spot first.' },
    { label: 'Grip alignment', text: 'Match both hands to the clubface. Grip pressure slightly firmer than a full iron, but still calm. V lines matched.' },
    { label: 'Stance and alignment', text: 'Right foot back about a quarter shoe to half a shoe. Stance slightly narrower than full iron. Body organised around the low start line.' },
    { label: 'Ball position', text: 'Centre or just back of centre.' },
    { label: 'Shaft / handle', text: 'Handle slightly ahead of the ball.' },
    { label: 'Feet and pressure', text: 'Pressure through inside toes, favouring lead side.' },
    { label: 'Posture', text: 'Athletic posture, chest over ball, arms connected.' },
    { label: 'Eye focus', text: 'Look at the front of the ball or grass just forward/outside-right.' },
    { label: 'Takeaway', text: 'Compact and smooth. Chest turns the club back.' },
    { label: 'Wrist hinge', text: 'Small, controlled wrist hinge. Less than a full 90-degree hinge. Enough set for structure, with the face staying stable.' },
    { label: 'Backswing', text: '9 o’clock backswing. Body turns, arms stay connected.' },
    { label: 'Transition', text: 'Pressure moves firmly into lead side as the arms fall into position. Chest turns through low.' },
    { label: 'Strike', text: 'Ball first, then turf. Handle stays ahead, chest keeps rotating.' },
    { label: 'Follow-through', text: 'Shorter, lower finish. Lead arm feels long.' },
  ],
  bump: [
    { label: 'Shot goal', text: 'Main swing thought: Face first. Grip down. Separate hands. Quiet wrists. Brush and roll. Simple cue: Aim face, clock length, brush and roll. Goal is a low bump-and-run that lands early and rolls predictably.' },
    { label: 'Clock length', text: '', fullText: 'Full bump: about 8 o’clock backswing. Keep the same smooth putting rhythm.', halfText: 'Half bump: about 7 o’clock backswing. Keep the same smooth putting rhythm.' },
    { label: 'Pre-shot routine', text: 'Stand behind the ball. Pick landing spot first, then final target. Picture the ball landing low and rolling like a putt. Make one rehearsal matching this shot’s clock length. Step in with clubface first.' },
    { label: 'Clubface alignment', text: 'Aim the clubface at the landing spot first.' },
    { label: 'Grip alignment', text: 'Grip down for control. Separate the hands slightly to minimise wrist hinge. Hands match the clubface. Grip pressure calm and stable.' },
    { label: 'Stance and alignment', text: 'Narrow stance. Right foot only slightly back. Setup feels simple, stable and slightly lead-side.' },
    { label: 'Ball position', text: 'Middle to slightly back of middle.' },
    { label: 'Shaft / handle', text: 'Handle slightly ahead of the ball.' },
    { label: 'Feet and pressure', text: 'Pressure through inside toes, favouring lead side.' },
    { label: 'Posture', text: 'Stand a touch taller and closer than a full shot. Arms hang naturally. Chest controls the motion.' },
    { label: 'Eye focus', text: 'Look at the front of the ball or the grass just in front.' },
    { label: 'Takeaway', text: 'Small, smooth, putting-style takeaway. Chest and shoulders move the club.' },
    { label: 'Wrist hinge', text: 'No active wrist hinge. Wrists stay quiet and structured. Separate hands help keep the stroke stable.' },
    { label: 'Backswing', text: '', fullText: 'Match the full bump length: about 8 o’clock.', halfText: 'Match the half bump length: about 7 o’clock.' },
    { label: 'Transition', text: 'Smooth change of direction. Chest keeps moving through the strike.' },
    { label: 'Strike', text: 'Brush the grass after the ball. Ball pops forward low and starts rolling.' },
    { label: 'Follow-through', text: 'Finish slightly longer than the backswing. Handle and lead arm continue toward the landing spot.' },
  ],
  pitch: [
    { label: 'Shot goal', text: 'Main swing thought: Face first. Soft hands. Use the bounce. Brush under the ball. Simple cue: Aim face, hinge softly, chest through, brush under. Goal is a controlled pitch with predictable launch, clean turf contact and distance controlled by clock length.' },
    { label: 'Clock length', text: '', fullText: 'Full pitch: about 9–10 o’clock with a fuller natural hinge. Keep the same smooth rhythm.', halfText: 'Half pitch: about 8 o’clock with a smaller, softer hinge. Keep the same smooth rhythm.' },
    { label: 'Pre-shot routine', text: 'Stand behind the ball. Pick landing spot and final target. Picture the ball flying to the landing spot with the right height and stop pattern. Make one rehearsal feeling soft hands, bounce brushing the turf and chest turning through. Step in with clubface first.' },
    { label: 'Clubface alignment', text: 'Aim the clubface at the landing spot first. Build the body around the face.' },
    { label: 'Grip alignment', text: 'Hands match the clubface. Grip pressure soft and even. V lines matched. Keep high clubface awareness because small face changes affect launch and spin.' },
    { label: 'Stance and alignment', text: 'Feet fairly narrow. Right foot only slightly back. Body feels calm and organised.' },
    { label: 'Ball position', text: 'Around centre. Slightly forward for a softer or higher pitch; slightly back for a lower pitch.' },
    { label: 'Shaft / handle', text: 'Handle neutral to slightly ahead. Keep enough loft available so the bounce can work.' },
    { label: 'Feet and pressure', text: 'Pressure through inside toes, favouring lead side.' },
    { label: 'Posture', text: 'Athletic but relaxed. Chest over ball. Arms hang naturally.' },
    { label: 'Eye focus', text: 'Normal or soft lie: bottom of or just under the ball; feel the bounce brush underneath. Tight or firm lie: bottom-front of the ball or grass just under/after it.' },
    { label: 'Takeaway', text: 'Smooth, connected takeaway. Chest turns the club back. Hands stay soft.' },
    { label: 'Wrist hinge', text: '', fullText: 'Soft, natural wrist hinge that can build close to 90 degrees by the top of the full-pitch backswing.', halfText: 'Soft, smaller wrist hinge matched to the shorter half-pitch clock length.' },
    { label: 'Backswing', text: '', fullText: 'Full pitch uses 9–10 o’clock with more hinge. Length controls distance.', halfText: 'Half pitch uses 8 o’clock with a softer, smaller hinge. Length controls distance.' },
    { label: 'Transition', text: 'Pressure stays lead side as the arms fall naturally. Chest keeps turning so the bounce can brush under the ball.' },
    { label: 'Strike', text: 'Brush the turf under or after the ball. Let the loft and bounce slide through.' },
    { label: 'Follow-through', text: 'Finish length matches shot size. Chest faces target. Lead arm feels long and soft.' },
  ],
  chip: [
    { label: 'Shot goal', text: 'Main swing thought: Face first. Grip down. Separate hands. Toe strike. Land it. Simple cue: Aim face, stand close, toe down, putt it. Goal is a simple chip that lands on the chosen spot and rolls out predictably.' },
    { label: 'Clock length', text: '', fullText: 'Full chip: about 7:30–8 o’clock. Keep the same putting rhythm.', halfText: 'Half chip: about 7 o’clock. Keep the same putting rhythm.' },
    { label: 'Pre-shot routine', text: 'Stand behind the ball. Pick landing spot, then final target. Picture first bounce and roll. Make one putting-style rehearsal with quiet wrists and a steady handle. Step in with clubface first.' },
    { label: 'Clubface alignment', text: 'Aim the clubface at the landing spot first.' },
    { label: 'Grip alignment', text: 'Grip down. Separate the hands slightly to minimise wrist hinge. Hands match the clubface. Grip pressure calm and stable.' },
    { label: 'Stance and alignment', text: 'Stand closer to the ball. Very narrow stance. Right foot does not need to be back. Toe of the club feels slightly down.' },
    { label: 'Ball position', text: 'Middle to slightly back of middle.' },
    { label: 'Shaft / handle', text: 'Handle slightly ahead of the ball.' },
    { label: 'Feet and pressure', text: 'Pressure through inside toes, favouring lead side.' },
    { label: 'Posture', text: 'Stand closer and a touch taller. Arms hang softly. Chest and shoulders control the stroke.' },
    { label: 'Eye focus', text: 'Look at the front of the ball or the grass just ahead.' },
    { label: 'Takeaway', text: 'Putting-style takeaway with chest and shoulders. Hands stay quiet.' },
    { label: 'Wrist hinge', text: 'No wrist hinge. This is a putting motion. Separated hands help keep the wrists quiet and handle stable.' },
    { label: 'Strike', text: 'Strike with the toe area of the club. The toe-down setup helps the ball come off softer and roll predictably.' },
    { label: 'Follow-through', text: 'Finish slightly longer than the backswing. Handle, chest and lead arm continue toward the landing spot.' },
  ],
};

export function resolveTechniqueNotes(notes: ShotTechniqueNote[], power: string): Array<{ label: string; text: string }> {
  return notes.map(note => ({
    label: note.label,
    text: power === 'full' ? (note.fullText ?? note.text) : power === '9pm' ? (note.halfText ?? note.text) : note.text,
  })).filter(note => note.text.trim());
}
