import { PuttingDrill, PuttingMetric } from '@/types/putting';

export const PUTTING_METRIC_LABELS: Record<PuttingMetric, string> = {
  startLineStrike: 'Start Line & Strike',
  paceTouch: 'Pace & Touch',
  conversionPressure: 'Conversion & Pressure',
};

export const LOCKED_INDOOR_DRILLS: PuttingDrill[] = [
  {
    id: '11111111-1111-4111-8111-111111111111',
    user_id: null,
    category: 'indoor',
    name: 'Start-Line Gate',
    purpose: 'Tests face aim and start direction.',
    setup: 'Set a gate about 30 cm in front of the ball. Putt from 1.5 m.',
    reps: 20,
    scoring_inputs: [
      { id: 'through_gate_holed', label: 'Through gate and holed or hit target', points: 2 },
      { id: 'through_gate_miss', label: 'Through gate but missed target', points: 1 },
      { id: 'missed_gate', label: 'Hit or missed gate', points: 0 },
    ],
    max_score: 40,
    scaled: false,
    scaled_max: null,
    level_bands: [
      { min: 0, max: 20, label: 'Needs work' },
      { min: 21, max: 31, label: 'Decent' },
      { min: 32, max: 35, label: 'Good' },
      { min: 36, max: 40, label: 'Excellent' },
    ],
    recommendation: 'Rebuild the face-first routine and roll through a near start spot.',
    is_builtin: true,
    sort_order: 10,
    scoring_mode: 'standard',
  },
  {
    id: '99999999-9999-4999-8999-999999999999',
    user_id: null,
    category: 'indoor',
    name: 'Spot Roll Drill',
    purpose: 'Tests whether you can start the ball over a chosen spot.',
    setup: 'Place a coin, tape mark, or small flat object 10-30 cm in front of the ball on the intended start line. Putt from 1-2 m.',
    reps: 20,
    scoring_inputs: [
      { id: 'over_spot_holed', label: 'Over spot and holed or hit target', points: 2 },
      { id: 'over_spot_miss', label: 'Over spot but missed target', points: 1 },
      { id: 'missed_spot', label: 'Missed the spot', points: 0 },
    ],
    max_score: 40,
    scaled: false,
    scaled_max: null,
    level_bands: [
      { min: 0, max: 20, label: 'Needs work' },
      { min: 21, max: 31, label: 'Decent' },
      { min: 32, max: 35, label: 'Good' },
      { min: 36, max: 40, label: 'Excellent' },
    ],
    recommendation: 'Pick the spot. Roll it over the spot.',
    is_builtin: true,
    sort_order: 15,
    scoring_mode: 'standard',
  },
  {
    id: '22222222-2222-4222-8222-222222222222',
    user_id: null,
    category: 'indoor',
    name: 'Distance Ladder',
    purpose: 'Tests pace and stroke length.',
    setup: 'Set finish zones at 1 m, 1.75 m, and 2.5 m. Make each zone about 20-30 cm deep.',
    reps: 15,
    scoring_inputs: [
      { id: 'in_zone', label: 'Inside correct zone', points: 1 },
      { id: 'missed_zone', label: 'Short or long', points: 0 },
    ],
    max_score: 15,
    scaled: false,
    scaled_max: null,
    level_bands: [
      { min: 0, max: 7, label: 'Needs work' },
      { min: 8, max: 11, label: 'Decent' },
      { min: 12, max: 13, label: 'Good' },
      { min: 14, max: 15, label: 'Excellent' },
    ],
    recommendation: 'Spend the next session on same tempo with a bigger or smaller stroke.',
    is_builtin: true,
    sort_order: 20,
    scoring_mode: 'standard',
  },
  {
    id: '33333333-3333-4333-8333-333333333333',
    user_id: null,
    category: 'indoor',
    name: '1 m Automatic Putts',
    purpose: 'Tests repeatable short-putt conversion.',
    setup: 'Set a straight 1 m putt to a cup, mug, putting hole, or small target.',
    reps: 20,
    scoring_inputs: [
      { id: 'made', label: 'Holed or hit target', points: 1 },
      { id: 'missed', label: 'Miss', points: 0 },
    ],
    max_score: 20,
    scaled: false,
    scaled_max: null,
    level_bands: [
      { min: 0, max: 12, label: 'Needs work' },
      { min: 13, max: 16, label: 'Decent' },
      { min: 17, max: 18, label: 'Good' },
      { min: 19, max: 20, label: 'Excellent' },
    ],
    recommendation: 'Keep the same routine and start it straight from 1 m.',
    is_builtin: true,
    sort_order: 30,
    scoring_mode: 'standard',
  },
  {
    id: '44444444-4444-4444-8444-444444444444',
    user_id: null,
    category: 'indoor',
    name: 'Putter Gate Stroke',
    purpose: 'Tests clean stroke path and centred contact.',
    setup: 'Set two objects just wider than your putter head. Place the ball in the middle. Putt from 1.5 m.',
    reps: 20,
    scoring_inputs: [
      { id: 'clean_holed', label: 'Clean stroke, holed putt', points: 2 },
      { id: 'clean_miss', label: 'Clean stroke, miss', points: 1 },
      { id: 'hit_gate', label: 'Hit the gate', points: 0 },
    ],
    max_score: 40,
    scaled: false,
    scaled_max: null,
    level_bands: [
      { min: 0, max: 20, label: 'Needs work' },
      { min: 21, max: 28, label: 'Decent' },
      { min: 29, max: 34, label: 'Good' },
      { min: 35, max: 40, label: 'Excellent' },
    ],
    recommendation: 'Prioritise clean gate contact before worrying about make rate.',
    is_builtin: true,
    sort_order: 40,
    scoring_mode: 'standard',
  },
  {
    id: '55555555-5555-4555-8555-555555555555',
    user_id: null,
    category: 'indoor',
    name: 'Around-the-Clock Short Putts',
    purpose: 'Tests short putts from different angles.',
    setup: 'Place 4 balls around a hole/cup/target at 1 m. Repeat the full circle 5 times.',
    reps: 20,
    scoring_inputs: [
      { id: 'made', label: 'Holed or hit target', points: 1 },
      { id: 'missed', label: 'Miss', points: 0 },
    ],
    max_score: 20,
    scaled: false,
    scaled_max: null,
    level_bands: [
      { min: 0, max: 12, label: 'Needs work' },
      { min: 13, max: 16, label: 'Decent' },
      { min: 17, max: 18, label: 'Good' },
      { min: 19, max: 20, label: 'Excellent' },
    ],
    recommendation: 'Use the same routine across different looks at the same distance.',
    is_builtin: true,
    sort_order: 50,
    scoring_mode: 'standard',
  },
  {
    id: '66666666-6666-4666-8666-666666666666',
    user_id: null,
    category: 'indoor',
    name: 'Leapfrog Lag Putting',
    purpose: 'Tests touch and small distance changes.',
    setup: 'Start from 1 m. Each ball must finish past the previous ball but inside the 2.5 m end boundary.',
    reps: 10,
    scoring_inputs: [
      { id: 'successful_leap', label: 'Past previous, inside boundary', points: 1 },
      { id: 'failed_leap', label: 'Short of previous or past 2.5 m', points: 0 },
    ],
    max_score: 10,
    scaled: false,
    scaled_max: null,
    level_bands: [
      { min: 0, max: 4, label: 'Needs work' },
      { min: 5, max: 7, label: 'Decent' },
      { min: 8, max: 9, label: 'Good' },
      { min: 10, max: 10, label: 'Excellent' },
    ],
    recommendation: 'Practise landing the ball just past the previous finish.',
    is_builtin: true,
    sort_order: 60,
    scoring_mode: 'standard',
  },
  {
    id: '77777777-7777-4777-8777-777777777777',
    user_id: null,
    category: 'indoor',
    name: 'Random Distance Call',
    purpose: 'Tests changing distance on demand.',
    setup: 'Set finish zones at 1 m, 1.75 m, and 2.5 m. Randomly call the target before each putt.',
    reps: 15,
    scoring_inputs: [
      { id: 'called_zone', label: 'Finished in called zone', points: 1 },
      { id: 'missed_called_zone', label: 'Missed called zone', points: 0 },
    ],
    max_score: 15,
    scaled: false,
    scaled_max: null,
    level_bands: [
      { min: 0, max: 7, label: 'Needs work' },
      { min: 8, max: 11, label: 'Decent' },
      { min: 12, max: 13, label: 'Good' },
      { min: 14, max: 15, label: 'Excellent' },
    ],
    recommendation: 'Rehearse see it, feel it, roll it before each changed distance.',
    is_builtin: true,
    sort_order: 70,
    scoring_mode: 'standard',
  },
  {
    id: '88888888-8888-4888-8888-888888888888',
    user_id: null,
    category: 'indoor',
    name: 'Pressure Ladder',
    purpose: 'Tests make rate when the score matters.',
    setup: 'Putts at 0.5 m, 1 m, 1.5 m, 2 m, and 2.5 m. Hole it to move back; miss and go back one step.',
    reps: 1,
    scoring_inputs: [
      { id: 'level_0', label: 'No level completed', points: 0 },
      { id: 'level_1', label: '0.5 m completed', points: 1 },
      { id: 'level_2', label: '1 m completed', points: 2 },
      { id: 'level_3', label: '1.5 m completed', points: 3 },
      { id: 'level_4', label: '2 m completed', points: 4 },
      { id: 'level_5', label: '2.5 m completed', points: 5 },
    ],
    max_score: 5,
    scaled: false,
    scaled_max: null,
    level_bands: [
      { min: 0, max: 2, label: 'Needs work' },
      { min: 3, max: 3, label: 'Decent' },
      { min: 4, max: 4, label: 'Good' },
      { min: 5, max: 5, label: 'Excellent' },
    ],
    recommendation: 'Slow down the routine and treat each putt as a single full commitment.',
    is_builtin: true,
    sort_order: 80,
    scoring_mode: 'pressure_ladder',
  },
];

export const INDOOR_PRACTICE_SETS = [
  {
    id: 'set-a',
    name: 'Set A - Start Line + Short Makes',
    description: 'Face aim, start direction, clean stroke, and short-putt conversion under pressure.',
    drillNames: ['Start-Line Gate', 'Spot Roll Drill', 'Putter Gate Stroke', '1 m Automatic Putts'],
  },
  {
    id: 'set-b',
    name: 'Set B - Pace + Touch',
    description: 'Distance control, touch, and adapting to different short putts.',
    drillNames: ['Distance Ladder', 'Leapfrog Lag Putting', 'Random Distance Call', 'Around-the-Clock Short Putts'],
  },
  {
    id: 'set-c',
    name: 'Set C - Stroke + Transfer',
    description: 'Balanced technique check without getting too technical.',
    drillNames: ['Spot Roll Drill', 'Putter Gate Stroke', 'Random Distance Call', 'Pressure Ladder'],
  },
  {
    id: 'full',
    name: 'Full Putting Test',
    description: 'Run the whole home putting battery.',
    drillNames: LOCKED_INDOOR_DRILLS.map(drill => drill.name),
  },
] as const;

export type IndoorPracticeSetId = (typeof INDOOR_PRACTICE_SETS)[number]['id'];

export const DRILL_METRIC_WEIGHTS: Record<string, Partial<Record<PuttingMetric, number>>> = {
  'Start-Line Gate': { startLineStrike: 1 },
  'Spot Roll Drill': { startLineStrike: 0.7, conversionPressure: 0.3 },
  'Distance Ladder': { paceTouch: 1 },
  '1 m Automatic Putts': { conversionPressure: 0.8, startLineStrike: 0.2 },
  'Putter Gate Stroke': { startLineStrike: 0.7, conversionPressure: 0.3 },
  'Around-the-Clock Short Putts': { conversionPressure: 1 },
  'Leapfrog Lag Putting': { paceTouch: 1 },
  'Random Distance Call': { paceTouch: 1 },
  'Pressure Ladder': { conversionPressure: 1 },
};

export function mergeLockedIndoorDrills(remoteDrills: PuttingDrill[]): PuttingDrill[] {
  const lockedIds = new Set(LOCKED_INDOOR_DRILLS.map(drill => drill.id));
  const unlockedRemote = remoteDrills.filter(drill => !lockedIds.has(drill.id));
  return [...LOCKED_INDOOR_DRILLS, ...unlockedRemote].sort((a, b) => a.sort_order - b.sort_order);
}
